services:
  postgres:
    image: postgres:16
    container_name: posto-combustivel
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: posto-combustivel
    volumes:
      - transacao_simplificada_data:/var/lib/postgresql/data

volumes:
  transacao_simplificada_data: