spring:
  application:
    name: posto-combustivel

  datasource:
    url: jdbc:postgresql://localhost:5432/posto-combustivel
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true